/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import inf.mainframe;

import javax.swing.JOptionPane;

/**
 *
 * @author PREDATOR
 */
public class login extends javax.swing.JFrame {

   

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        upassword = new javax.swing.JPasswordField();
        logingbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        signinbtn = new javax.swing.JButton();
        Hinttext2 = new javax.swing.JLabel();
        Hinttext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Here");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, -1));

        uname.setForeground(new java.awt.Color(0, 51, 255));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 240, -1));

        upassword.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(upassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 240, -1));

        logingbtn.setBackground(new java.awt.Color(204, 255, 255));
        logingbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        logingbtn.setForeground(new java.awt.Color(0, 0, 204));
        logingbtn.setText("Login");
        logingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logingbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logingbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("User Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        signinbtn.setBackground(new java.awt.Color(204, 255, 255));
        signinbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        signinbtn.setForeground(new java.awt.Color(0, 0, 204));
        signinbtn.setText("Hint");
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        Hinttext2.setFont(new java.awt.Font("SimSun", 3, 12)); // NOI18N
        Hinttext2.setForeground(new java.awt.Color(204, 0, 0));
        Hinttext2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Hinttext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 400, 30));

        Hinttext.setFont(new java.awt.Font("SimSun", 3, 12)); // NOI18N
        Hinttext.setForeground(new java.awt.Color(204, 0, 0));
        Hinttext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hinttext.setText("Click Hint for tips");
        jPanel1.add(Hinttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 400, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        setSize(new java.awt.Dimension(535, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void logingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logingbtnActionPerformed
        String UserName;
        String pw;
        
        UserName = uname.getText();
        pw = upassword.getText();
        
        if(UserName.equals("SC/2020/11528")||UserName.equals("SC/2020/11524")||UserName.equals("SC/2020/11580")||UserName.equals("SC/2020/11513")&& pw.equals("1234")){
        
        mainframe b1 = new mainframe();
        b1.setVisible(true);
        this.dispose();
    }else{
            JOptionPane.showMessageDialog(null, "Error : Username or passward is incorrect");
        
        }
    }//GEN-LAST:event_logingbtnActionPerformed

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
       Hinttext.setText("Use your ID No for the username ; Password Hint - 1234");
       Hinttext2.setText("(Only members of our team can login )");
    }//GEN-LAST:event_signinbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hinttext;
    private javax.swing.JLabel Hinttext2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logingbtn;
    private javax.swing.JButton signinbtn;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upassword;
    // End of variables declaration//GEN-END:variables
}
