/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;


import java.io.*;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;



public class mainframe extends javax.swing.JFrame {
    
    ArrayList<String> studentid = new ArrayList<String>();
    ArrayList<Integer> studentmark = new ArrayList<Integer>();
    ArrayList<Character> grade = new ArrayList<Character>(); 
    ArrayList<String> result = new ArrayList<String>();
     
     String stuid;
     int stumark;
     char grd;
     String rslt;
     
     
   
  public void update(){
 
     
    result.removeAll(result);
     
     Integer maxnumber =  Collections.max(studentmark);
     System.out.println("student marks : " + studentmark);
     Integer minnumber =  Collections.min(studentmark);
     Double average = averagefromarrayList(studentmark);
     
        
     for(int i =0;i<studentmark.size();i++){
          if(studentmark.get(i)>=75){
         grd = 'A' ;
        }else if (studentmark.get(i)>=65){
        grd = 'B';
        }else if (studentmark.get(i)>=55){
        grd = 'C';
        }else if (studentmark.get(i)>=35){
        grd = 'W';}
        else {
        grd = 'F';}
   
          grade.add(grd);
          
          result.add( studentid.get(i) +"-"+ studentmark.get(i) +"("+grade.get(i)+")" );
     }
     /*int j=0;
     //result.add(stuid +"-"+ stumark +"("+grd+")" );
     
        for( ;j<result.size();j++){    
        
            rslt=result.get(j);
     break;
     }   
     */
     
     rslt=String.join("\n", result);
     System.out.println("student grade : " + grade);
     System.out.println("student result : " + result);
     
     resultbox.setText("");
     String exitsentence = resultbox.getText();
     resultbox.setText(exitsentence+"No.of Students = "+ studentmark.size()+"\n"+"Maximum Mark = "+ maxnumber +"\n"+"Minimum Marks = "+ minnumber +"\n"+"Average Mark = "+ average +"\n"+"\n"+"\n"+"\n"+"*******************************************"+"\n"+"Student Index with Mark Grades"+"\n"+"\n"+"\n"+rslt+"\n" );
     
     
  }
    
 public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mrksbox = new javax.swing.JTextField();
        idnobox = new javax.swing.JTextField();
        adstubtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sturecodbox = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultbox = new javax.swing.JTextArea();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Marks Board");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Student Records");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Marks");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Index No");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        mrksbox.setBackground(new java.awt.Color(255, 255, 255));
        mrksbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mrksbox.setToolTipText("Enter the Subject Mark ( 0 -100 )");
        jPanel2.add(mrksbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, -1));

        idnobox.setBackground(new java.awt.Color(255, 255, 255));
        idnobox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idnobox.setToolTipText("Enter Student Index No");
        idnobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnoboxActionPerformed(evt);
            }
        });
        jPanel2.add(idnobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, -1));

        adstubtn.setBackground(new java.awt.Color(204, 255, 255));
        adstubtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adstubtn.setForeground(new java.awt.Color(102, 102, 102));
        adstubtn.setText("Add Student");
        adstubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adstubtnActionPerformed(evt);
            }
        });
        jPanel2.add(adstubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 130, 140, 30));

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Student Information");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        sturecodbox.setBackground(new java.awt.Color(255, 255, 255));
        sturecodbox.setColumns(20);
        sturecodbox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sturecodbox.setRows(5);
        jScrollPane1.setViewportView(sturecodbox);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 260));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 490));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Results");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, -1));

        resultbox.setBackground(new java.awt.Color(255, 255, 255));
        resultbox.setColumns(20);
        resultbox.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        resultbox.setRows(5);
        jScrollPane2.setViewportView(resultbox);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 350, 420));

        savebtn.setBackground(new java.awt.Color(153, 204, 255));
        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        savebtn.setText("Save Summary");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 120, 30));

        updatebtn.setBackground(new java.awt.Color(153, 204, 255));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatebtn.setText("Update Result");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, 30));

        clearbtn.setBackground(new java.awt.Color(153, 204, 255));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbtn.setText("Clear Student");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void idnoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnoboxActionPerformed
   
    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
     
     //clear text feild and text area
     idnobox.setText("");
     mrksbox.setText("");
     sturecodbox.setText("");
     resultbox.setText("");
     
     //clear all arraylist data
     studentid.removeAll(studentid);
     studentmark.removeAll(studentmark);
     grade.removeAll(grade);
      result.removeAll(result);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void adstubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adstubtnActionPerformed

     
     if(idnobox.getText().isEmpty()||mrksbox.getText().isEmpty()) {
     
         JOptionPane.showMessageDialog(null, "Please input student details");
     }else{
        
     //String stuid;
     int conditionMark;
     conditionMark = Integer.parseInt(mrksbox.getText());
     if(conditionMark<0 || conditionMark>100){
         JOptionPane.showMessageDialog(null, "Enter the Valid mark (Between 0-100)");
         mrksbox.setText("");
     }else{
    stuid = idnobox.getText();
    stumark = Integer.parseInt(mrksbox.getText());
    
    studentid.add(stuid);
    studentmark.add(stumark);
    
    
     idnobox.setText("");
     mrksbox.setText("");
     String exitsentence = sturecodbox.getText();
     sturecodbox.setText(exitsentence + stuid +"-"+ stumark +"\n" );
     }
     }
        
    }//GEN-LAST:event_adstubtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        if(sturecodbox.getText().isEmpty()) {
     
         JOptionPane.showMessageDialog(null, "Please Add student details and Update");
     }else{
        update();
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed

        if(resultbox.getText().isEmpty()) {
     
         JOptionPane.showMessageDialog(null, "Please get results and save your file");
     }else{
        
        
       try {
            File file = new File("results_summary.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            PrintWriter pw = new PrintWriter(file);
            pw.print(resultbox.getText());
            pw.close();
            
            JOptionPane.showMessageDialog(null, "Text File Saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: you can't write to txt file");
        
        }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adstubtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField idnobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mrksbox;
    private javax.swing.JTextArea resultbox;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextArea sturecodbox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void String() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
      //fine max no of the array list
     /*private static Integer findMmaxfromarralist(ArrayList<Integer> studentmark) {
            
       Integer max = Integer.MIN_VALUE;
       for(Integer number:studentmark){
        if(number>max){
        max = number;
        }
    }
      return max;
            
        
    }
   //fine min no of the arraylist
   private static Integer findminfromarralist(ArrayList<Integer> studentmark) {
        Integer min = Integer.MAX_VALUE;
       for(Integer number:studentmark){
        if(number<min){
        min = number;
        }
    }
      return min;
    }
*/
    //fine average of the arraylist
    private static double averagefromarrayList(ArrayList<Integer> studentmark){
       double total=0; 
      for(Integer av:studentmark){
      total += av;
      }
       
       
       return total/studentmark.size();
    }
    
     
    }
        

    
